In [1]:
import numpy as np
import pandas

arr1 = np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


In [2]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.array([np.arange(3), np.arange(start=6, stop=9)])


array([[0, 1, 2],
       [6, 7, 8]])

In [13]:
np.array([np.arange(3), np.arange(start=2, step=2, stop=7)])

array([[0, 1, 2],
       [2, 4, 6]])

In [14]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [16]:
np.arange(5, dtype=float)

array([0., 1., 2., 3., 4.])

In [20]:
np.array([11.2,23.22,51.223], dtype='int8')

array([11, 23, 51], dtype=int8)

In [24]:
np.array([[1,2,3],[2,3,4]]).ndim
# ndim: 维度

2

In [25]:
np.array([[1,2,3],[2,3,4]]).shape
# shape: 尺度--n行m列（n,m），返回一个元组

(2, 3)

In [26]:
np.array([[1,2,3],[2,3,4]]).size
# size： 元素个数

6

In [27]:
np.array([[1,2,3],[2,3,4]]).itemsize
# itemsize： 各元素的字节数大小

4

In [29]:
np.array([[1,2,3],[2,3,4]]).nbytes
# nbytes： 所有元素的字节数总和

24

In [30]:
np.array([[1,2,3],[2,3,4]]).T
# T：转置

array([[1, 2],
       [2, 3],
       [3, 4]])

In [39]:
a=np.arange(6).reshape(2,3)
print("a:", a)
b=a.flat
print("b:", b)
for i in b:
    print(i)
print("b[2]:", b[2])

a: [[0 1 2]
 [3 4 5]]
b: <numpy.flatiter object at 0x000002573B870BE0>
0
1
2
3
4
5
b[2]: 2


In [40]:
np.arange(5)[1:4]
# 切片

array([1, 2, 3])

In [58]:
a = np.arange(12).reshape(3,4)
print(a.reshape(4,3))

b = np.arange(12).reshape(3,4)
b.resize(4,3)
print(b)

# reshape是临时修改，并不作用于原数组
# resize是没有返回值的，而是直接作用于原数组

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [61]:
a = np.arange(6).reshape(2,3)
b = np.arange(start=2, stop=8).reshape(2,3)
print(a+2*b)

[[ 4  7 10]
 [13 16 19]]


In [63]:
np.hstack((a,b))
# 水平叠加

array([[0, 1, 2, 2, 3, 4],
       [3, 4, 5, 5, 6, 7]])

In [64]:
np.vstack((a,b))
# 垂直叠加

array([[0, 1, 2],
       [3, 4, 5],
       [2, 3, 4],
       [5, 6, 7]])

In [65]:
np.concatenate((a,b), axis=1)
# axis=1 为水平叠加

array([[0, 1, 2, 2, 3, 4],
       [3, 4, 5, 5, 6, 7]])

In [66]:
np.concatenate((a,b), axis=0)
# axis=0 为垂直叠加

array([[0, 1, 2],
       [3, 4, 5],
       [2, 3, 4],
       [5, 6, 7]])